#pragma once

namespace state {

/** Stable semantic notification emitted after an action executes. */
enum class ActionEvent {
  None,
  DoCPUCombatTurn,
  DoCombatAction,
  DoCombatActionCompletion,
  EndCombat,
  GoNextCombatTurn,
  ModifyAP,
  ModifyHP,
  MoveCharacter,
  PerformCharacterDefeated,
  PerformMeleeAttack,
  PerformSpellCast,
  RemoveCharacterFromMap,
  SetActiveCombatCharacter,
  StartCombat,
  PlaySound,
  UiAdjustEquippedRune,
  UiContinueSpecialEvent,
  UiDropInventoryItem,
  UiGiveInventoryItem,
  UiPickUpItem,
  UiPushFloatingNotification,
  UiRemoveFloatingNotification,
  UiReorderInventoryItem,
  UiSelectSpecialEventChoice,
  UiSelectSpellCast,
  UiSetCurrentPartyMember,
  UiSetCurrentPartyMemberInventory,
  UiSetCurrentPartyMemberMagic,
  UiSetSelectedPartyMemberId,
  UiSetSpellReady,
  UiToggleEquipInventoryItem,
  UiToggleManaSlotRune,
  UiUpdateHeldMove,
  UiCancelEquipRunes,
  UiCommitEquipRunes,
  UiRemoveLayer,
  UiShowLayerDropContext,
  UiShowLayerEquipRunes,
  UiShowLayerGiveContext,
  UiShowLayerInventory,
  UiShowLayerInventoryContext,
  UiShowLayerMagic,
  UiShowLayerPickUp,
  UiShowLayerPickupContext,
  UiShowLayerPopupText,
  UiShowLayerSpecialEvent,
  UiShowLayerSpellCast,
  UiShowLayerSpellInfo,
  CharacterSetSpriteIndexOffset,
  ClearTownEnemyAiResolving,
  ModifyPartyMemberHp,
  PerformTownMeleeAttack,
  TownEnemyAiAfterPlayerMove,
  TownEnemySeekAndMelee,
  WorldExamineAt,
  WorldInteractAt,
  WorldLoadActiveMap,
  WorldMoveActionAim,
  WorldMovePlayer,
  WorldSetActionAim,
  WorldSetActionMode,
  WorldSetCamera,
  WorldSetCameraMode,
  WorldSpawnDamageParticle,
  WorldSpawnPlayer,
  WorldSpawnPlayerAtMarker,
  WorldSpawnPlayerAtXY,
  WorldSpawnProjectile,
  WorldTalkAt,
  WorldTravel,
};

} // namespace state
