#!/usr/bin/env bash
# Write a machine-local .clangd for the current toolchain.
# On MSYS2 UCRT64, prefer Clang's resource dir over GCC intrinsics so clangd
# does not hit builtin/intrinsic conflicts (__rdtsc, _xgetbv, etc.).
# Editors must spawn clangd.exe directly. Wrappers (.cmd or an _execv shim)
# break the LSP pipe on Windows.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/.clangd"
DB_REL="build/cmake/dev-debug"
DB_ABS="${ROOT}/${DB_REL}/compile_commands.json"
SETTINGS="${ROOT}/.vscode/settings.json"

to_clangd_path() {
  local path="$1"
  if command -v cygpath >/dev/null 2>&1; then
    cygpath -m "${path}"
  else
    printf '%s\n' "${path}"
  fi
}

discover_pch_path() {
  if [[ ! -f "${DB_ABS}" ]]; then
    return 0
  fi
  local match
  match="$(grep -oE -- '-include[[:space:]]+[^[:space:]]+cmake_pch[^[:space:]]*' "${DB_ABS}" | head -n 1 || true)"
  if [[ -n "${match}" ]]; then
    printf '%s\n' "${match#-include }"
  fi
}

is_msys2_ucrt() {
  case "$(uname -s)" in
    MINGW*|MSYS*) return 0 ;;
    *) return 1 ;;
  esac
}

point_editor_at_clangd() {
  local clangd_bin clangd_win
  clangd_bin="$(command -v clangd || true)"
  if [[ -z "${clangd_bin}" || ! -f "${SETTINGS}" ]]; then
    return 0
  fi
  clangd_win="$(to_clangd_path "${clangd_bin}")"
  if grep -q '"clangd.path"' "${SETTINGS}"; then
    sed -i "s|\"clangd.path\": \"[^\"]*\"|\"clangd.path\": \"${clangd_win}\"|" "${SETTINGS}"
  fi
  echo "  editor clangd.path: ${clangd_win}"
}

write_header() {
  cat <<EOF
# Generated by scripts/generate-clangd-config.sh - do not edit.
# Re-run after setup-dev or when your MSYS2/toolchain prefix changes.
CompileFlags:
  CompilationDatabase: ${DB_REL}
  Remove:
    - -include
    - -Winvalid-pch
EOF
}

pch_path="$(discover_pch_path || true)"
prefix=""

{
  write_header
  if [[ -n "${pch_path}" ]]; then
    printf '    - %s\n' "${pch_path}"
  fi

  if is_msys2_ucrt; then
    if ! command -v clang++ >/dev/null 2>&1; then
      echo "error: clang++ is required for clangd on MSYS2 UCRT64." >&2
      echo "Install with: pacman -S mingw-w64-ucrt-x86_64-clang mingw-w64-ucrt-x86_64-clang-tools-extra" >&2
      exit 1
    fi
    if ! command -v clangd >/dev/null 2>&1; then
      echo "error: clangd is required on MSYS2 UCRT64." >&2
      echo "Install with: pacman -S mingw-w64-ucrt-x86_64-clang-tools-extra" >&2
      exit 1
    fi

    prefix="${MINGW_PREFIX:-}"
    if [[ -z "${prefix}" ]]; then
      prefix="$(cd "$(dirname "$(command -v c++)")/.." && pwd)"
    fi
    cxx_ver="$("${CXX:-c++}" -dumpversion)"
    resource_dir="$(clang++ -print-resource-dir)"
    win_prefix="$(to_clangd_path "${prefix}")"
    win_resource="$(to_clangd_path "${resource_dir}")"
    triple="x86_64-w64-mingw32"

    if [[ ! -d "${prefix}/include/c++/${cxx_ver}" ]]; then
      echo "error: libstdc++ headers not found at ${prefix}/include/c++/${cxx_ver}" >&2
      exit 1
    fi
    if [[ ! -d "${resource_dir}/include" ]]; then
      echo "error: Clang resource includes not found under ${resource_dir}" >&2
      exit 1
    fi

    cat <<EOF
  Add:
    - --target=x86_64-w64-windows-gnu
    - -resource-dir=${win_resource}
    - -isystem
    - ${win_prefix}/include/c++/${cxx_ver}
    - -isystem
    - ${win_prefix}/include/c++/${cxx_ver}/${triple}
    - -isystem
    - ${win_prefix}/include/c++/${cxx_ver}/backward
    - -isystem
    - ${win_resource}/include
    - -isystem
    - ${win_prefix}/include
EOF
  fi

  cat <<EOF

Index:
  Background: Build
EOF
} > "${OUT}"

echo "Wrote ${OUT}"
if is_msys2_ucrt; then
  point_editor_at_clangd
  echo "  toolchain: $(to_clangd_path "${prefix}")"
fi
